//
// Created by Evan Shaw on 4/25/23.
//

#ifndef CPP_TEST_BOOLEANOPERATIONTYPEENUM_H
#define CPP_TEST_BOOLEANOPERATIONTYPEENUM_H

enum BooleanOperationType {
	BOOLEAN_OPERATION_TYPE_EQUAL_TO,
	BOOLEAN_OPERATION_TYPE_NOT_EQUAL,
	BOOLEAN_OPERATION_TYPE_GREATER_THAN,
	BOOLEAN_OPERATION_TYPE_GREATER_THAN_OR_EQUAL_TO,
	BOOLEAN_OPERATION_TYPE_LESS_THAN,
	BOOLEAN_OPERATION_TYPE_LESS_THAN_OR_EQUAL_TO,
    BOOLEAN_OPERATION_TYPE_SPECIAL_NEGATE_MOVE
};

#endif //CPP_TEST_BOOLEANOPERATIONTYPEENUM_H
